--subset ids
WINDUTC_DATA_1 = 1
WINDUTC_DATA_2 = 2
WINDUTC_DATA_3 = 3
WINDUTC_NETWORKENTRY = 4
WINDUTC_NETWORKSTART = 5
WINDUTC_NETWORKCONNECT = 6
WINDUTC_NETWORKCONNECTSTATUS = 7
WINDUTC_DOWNLOAD = 8
--WINDUTC_DAFIF = 8
WINDUTC_CONFIG = 9

XTKTKEKEY_1   = 10
XTKTKEKEY_2   = 11
XTKTKEKEY_3   = 12
XTKTKEKEY_4   = 13
XTKTKEKEY_5   = 14
XTKTKEKEY_6   = 15
XTKTKEKEY_7   = 16

GSTKNAVM_1    = 21
--GSTKNAVM_2    = 22

PP_1          = 30
PP_2          = 31

DISTBRGTIME_1 = 40
DISTBRGTIME_2 = 41
DISTBRGTIME_3 = 42

WPTGT_1       = 50
WPTGT_2       = 51

DATUMROUTE_1  = 60
DATUMROUTE_2  = 61
DATUMROUTE_FP_1  = 62
DATUMROUTE_FP_2  = 63
DATUMROUTE_FP_3  = 64
DATUMROUTE_WP  = 65
DATUMROUTE_IAP  = 66
DATUMROUTE_RTCONSEC  = 67

F1_SELECTION  = 70
F1_DIRECTTO_1  = 71
F1_DIRECTTO_2  = 72
F1_OBSHOLD_1  = 73
F1_OBSHOLD_2  = 74
F1_MESSAGE  = 75
F1_MAHP  = 76
F1_VECTORTOFINAL_1  = 77
F1_VECTORTOFINAL_2  = 78

POWERUP_1 = 100
POWERUP_2 = 101

pagetable =
{
    WINDUTC_DATA_1 ,
    WINDUTC_DATA_2 ,
    WINDUTC_DATA_3 ,
    WINDUTC_NETWORKENTRY,
    WINDUTC_NETWORKSTART,
    WINDUTC_NETWORKCONNECT,
    WINDUTC_NETWORKCONNECTSTATUS,
    WINDUTC_DOWNLOAD ,
    --WINDUTC_DAFIF ,
    WINDUTC_CONFIG ,
    XTKTKEKEY_1   ,
    XTKTKEKEY_2   ,
    XTKTKEKEY_3   ,
    XTKTKEKEY_4 ,
    XTKTKEKEY_5 ,
    XTKTKEKEY_6 ,
    XTKTKEKEY_7 ,
    GSTKNAVM_1  ,
    --GSTKNAVM_2  ,
    PP_1        ,
    PP_2        ,
    DISTBRGTIME_1,
    DISTBRGTIME_2,
    DISTBRGTIME_3,
    WPTGT_1     ,
    WPTGT_2     ,
    DATUMROUTE_1,
    DATUMROUTE_2,
    DATUMROUTE_FP_1,
    DATUMROUTE_FP_2,
    DATUMROUTE_FP_3,
    DATUMROUTE_WP,
    DATUMROUTE_IAP,
    DATUMROUTE_RTCONSEC,
    F1_SELECTION,
    F1_DIRECTTO_1,
    F1_DIRECTTO_2,
    F1_OBSHOLD_1,
    F1_OBSHOLD_2,
    F1_MESSAGE,
    F1_MAHP,
    F1_VECTORTOFINAL_1,
    F1_VECTORTOFINAL_2,
    POWERUP_1,
    POWERUP_2,
}

pagesMore =
{
    WINDUTC_DATA_1 ,
    WINDUTC_DATA_2 ,
    --XTKTKEKEY_1   ,
    --XTKTKEKEY_2   ,
    --XTKTKEKEY_3   ,
    --XTKTKEKEY_4 ,
    --XTKTKEKEY_5 ,
    --XTKTKEKEY_6 ,
    --GSTKNAVM_1  ,
    PP_1        ,
    DISTBRGTIME_1,
    DISTBRGTIME_2,
    WPTGT_1     ,
    DATUMROUTE_1,
    DATUMROUTE_FP_1,
    DATUMROUTE_FP_2,
    F1_DIRECTTO_1,
    F1_OBSHOLD_1,
}

pagesEnd =
{
    WINDUTC_DATA_3 ,
    WINDUTC_NETWORKENTRY ,
    WINDUTC_NETWORKSTART ,
    WINDUTC_NETWORKCONNECTSTATUS,
    WINDUTC_CONFIG ,
    --WINDUTC_DAFIF ,
    WINDUTC_DOWNLOAD ,
    --XTKTKEKEY_7 ,
    --GSTKNAVM_2  ,
    PP_2        ,
    DISTBRGTIME_3,
    WPTGT_2     ,
    DATUMROUTE_2,
    F1_DIRECTTO_2,
    F1_OBSHOLD_2,
}

pagesOK =
{
    POWERUP_1,
}